"""
booking_repo.py - Data access layer for booking operations.

This module provides the BookingRepository class which handles all database
interactions related to the bookings table, including creation, retrieval,
updates, and various filtered queries needed by the BookingService.
"""

from datetime import datetime
from backend.database import get_connection
from backend.models import Booking, BookingStatus


class BookingRepository:
    """Repository for managing Booking records in the SQLite database."""

    def _row_to_booking(self, row) -> Booking:
        """
        Converts a SQLite Row object into a Booking dataclass instance.

        Maps the status string to a BookingStatus enum value and the
        created_at string to a datetime object.

        Parameters:
            row: A sqlite3.Row object from a query result.

        Returns:
            A Booking dataclass instance with all fields populated.
        """
        return Booking(
            id=row["id"],
            time_slot_id=row["time_slot_id"],
            student_id=row["student_id"],
            lecturer_id=row["lecturer_id"],
            place=row["place"],
            status=BookingStatus(row["status"]),
            created_at=datetime.fromisoformat(row["created_at"]),
        )

    def create(self, booking: Booking) -> Booking:
        """
        Inserts a new booking record into the database.

        The booking's id and created_at fields are ignored on input since they
        are auto-generated by the database (AUTOINCREMENT and DEFAULT datetime).

        Parameters:
            booking: A Booking instance with time_slot_id, student_id,
                     lecturer_id, place, and status populated.

        Returns:
            A new Booking instance with the database-generated id and created_at.
        """
        with get_connection() as conn:
            cursor = conn.execute(
                """
                INSERT INTO bookings (time_slot_id, student_id, lecturer_id, place, status)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    booking.time_slot_id,
                    booking.student_id,
                    booking.lecturer_id,
                    booking.place,
                    booking.status.value,
                ),
            )
            booking_id = cursor.lastrowid

            row = conn.execute(
                "SELECT * FROM bookings WHERE id = ?", (booking_id,)
            ).fetchone()

            return self._row_to_booking(row)

    def find_by_id(self, booking_id: int):
        """
        Retrieves a single booking by its unique ID.

        Parameters:
            booking_id: The integer primary key of the booking to find.

        Returns:
            A Booking instance if found, or None if no booking exists with
            the given ID.
        """
        with get_connection() as conn:
            row = conn.execute(
                "SELECT * FROM bookings WHERE id = ?", (booking_id,)
            ).fetchone()

            if row is None:
                return None

            return self._row_to_booking(row)

    def update(self, booking: Booking) -> Booking:
        """
        Updates an existing booking's status, time_slot_id, and place.

        Uses the booking's id to locate the record and overwrites the
        status, time_slot_id, and place columns.

        Parameters:
            booking: A Booking instance with an existing id and updated fields.

        Returns:
            The updated Booking instance as read back from the database.
        """
        with get_connection() as conn:
            conn.execute(
                """
                UPDATE bookings
                SET status = ?, time_slot_id = ?, place = ?
                WHERE id = ?
                """,
                (
                    booking.status.value,
                    booking.time_slot_id,
                    booking.place,
                    booking.id,
                ),
            )

            row = conn.execute(
                "SELECT * FROM bookings WHERE id = ?", (booking.id,)
            ).fetchone()

            return self._row_to_booking(row)

    def find_by_slot_and_status(self, time_slot_id: int, lecturer_id: int, status: BookingStatus) -> list:
        """
        Retrieves all bookings for a specific time slot, lecturer, and status.

        Results are ordered by created_at ASC to maintain FIFO queue ordering,
        which is essential for the booking queue display.

        Parameters:
            time_slot_id: The ID of the time slot to filter by.
            lecturer_id: The ID of the lecturer to filter by.
            status: The BookingStatus enum value to filter by.

        Returns:
            A list of Booking instances matching the criteria, ordered by
            submission time (oldest first).
        """
        with get_connection() as conn:
            rows = conn.execute(
                """
                SELECT * FROM bookings
                WHERE time_slot_id = ? AND lecturer_id = ? AND status = ?
                ORDER BY created_at ASC
                """,
                (time_slot_id, lecturer_id, status.value),
            ).fetchall()

            return [self._row_to_booking(row) for row in rows]

    def count_accepted_on_date(self, lecturer_id: int, target_date) -> int:
        """
        Counts the number of accepted bookings for a lecturer on a specific date.

        Joins with the time_slots table to check the slot_date column, since
        the booking itself does not store the date directly.

        Parameters:
            lecturer_id: The ID of the lecturer to count bookings for.
            target_date: A date object (or string in YYYY-MM-DD format)
                         representing the calendar day to check.

        Returns:
            An integer count of accepted bookings for the lecturer on that date.
        """
        # Convert date object to string for SQLite comparison
        date_str = str(target_date)

        with get_connection() as conn:
            row = conn.execute(
                """
                SELECT COUNT(*) as cnt FROM bookings b
                JOIN time_slots ts ON b.time_slot_id = ts.id
                WHERE b.lecturer_id = ? AND b.status = ? AND ts.slot_date = ?
                """,
                (lecturer_id, BookingStatus.ACCEPTED.value, date_str),
            ).fetchone()

            return row["cnt"]

    def count_by_slot_and_status(self, time_slot_id: int, status: BookingStatus) -> int:
        """
        Counts the number of bookings for a given time slot with a specific status.

        This method does not filter by lecturer — it counts all bookings for the
        slot regardless of which lecturer they belong to. Used by
        BookingService.get_slot_status() to derive whether a slot is available,
        queued, or taken, and by get_pending_count() to show the queue size.

        Parameters:
            time_slot_id: The ID of the time slot to count bookings for.
            status: The BookingStatus enum value to filter by.

        Returns:
            An integer count of bookings matching the slot and status.
        """
        with get_connection() as conn:
            row = conn.execute(
                """
                SELECT COUNT(*) as cnt FROM bookings
                WHERE time_slot_id = ? AND status = ?
                """,
                (time_slot_id, status.value),
            ).fetchone()

            return row["cnt"]

    def find_by_student(self, student_id: int) -> list:
        """
        Retrieves all bookings made by a specific student.

        Parameters:
            student_id: The ID of the student whose bookings to retrieve.

        Returns:
            A list of Booking instances for the student, ordered by
            created_at descending (most recent first).
        """
        with get_connection() as conn:
            rows = conn.execute(
                """
                SELECT * FROM bookings
                WHERE student_id = ?
                ORDER BY created_at DESC
                """,
                (student_id,),
            ).fetchall()

            return [self._row_to_booking(row) for row in rows]

    def find_by_lecturer(self, lecturer_id: int) -> list:
        """
        Retrieves all bookings assigned to a specific lecturer.

        Parameters:
            lecturer_id: The ID of the lecturer whose bookings to retrieve.

        Returns:
            A list of Booking instances for the lecturer, ordered by
            created_at descending (most recent first).
        """
        with get_connection() as conn:
            rows = conn.execute(
                """
                SELECT * FROM bookings
                WHERE lecturer_id = ?
                ORDER BY created_at DESC
                """,
                (lecturer_id,),
            ).fetchall()

            return [self._row_to_booking(row) for row in rows]
